<?php

function asset_topic_placement_init() {

    // On any taxonomy edit-page or site_strucutre_taxonomy adding-page...
    if ( 
        strpos(request_uri(), 'taxonomy/term/') !== false && strpos(request_uri(), '/edit') !== false 
        || strpos(request_uri(), '/admin/structure/taxonomy/site_strucutre_taxonomy/add') !== false
        || strpos(request_uri(), '/admin/structure/taxonomy_manager/voc/site_strucutre_taxonomy') !== false
    ) {

        // Include asset_topic_placement.js
        drupal_add_js(drupal_get_path('module', 'asset_topic_placement') . '/jquery.waituntilexists.js', 'file');
        drupal_add_js(drupal_get_path('module', 'asset_topic_placement') . '/asset_topic_placement.js', 'file');
        drupal_add_css(drupal_get_path('module', 'asset_topic_placement') . '/asset_topic_placement.css', 'file');

    }
}

function asset_topic_placement_entityreference_view_widget_views_arguments_alter(&$arguments, $form_state) {

    $selectedAssetTopics = asset_topic_placement_findSelectedTopicsInForm(null, $form_state['values']['field_asset_topic_taxonomy']['und'][0]);
    $selectedIncNavPages = asset_topic_placement_findSelectedTopicsInForm(null, $form_state['values']['field_also_include_on_nav_page']['und'][0]);
    $arguments = array(
        0 => implode('+', array_merge($selectedAssetTopics, $selectedIncNavPages))
    );

    //error_log(__FUNCTION__ . ' is sending the following arguments to the View: ' . $arguments[0]);
}

function asset_topic_placement_findSelectedTopicsInForm($form_state, $recursiveUse = null) {

    if ( is_null($recursiveUse) ) {
        return asset_topic_placement_findSelectedTopicsInForm(null, $form_state['values']['field_asset_topic_taxonomy']['und'][0]);
    }

    $ret = array();

    foreach ( $recursiveUse as $eid => $data ) {
        if ( is_array($data) ) {
            $ret = array_merge(
                $ret, 
                asset_topic_placement_findSelectedTopicsInForm(null, $data)
            );
        } elseif ( is_string($data) || is_numeric($data) ) {
            if ( intval($data) != 0 ) {
                $ret[] = intval($data);
            }
        }
    }

    return $ret;
}