<?php

function asset_topic_placement_init() {

    // On any taxonomy edit-page or site_strucutre_taxonomy adding-page...
    if ( 
        strpos(request_uri(), 'taxonomy/term/') !== false && strpos(request_uri(), '/edit') !== false 
        || strpos(request_uri(), '/admin/structure/taxonomy/site_strucutre_taxonomy/add') !== false
    ) {

        // Include asset_topic_placement.js
        drupal_add_js(drupal_get_path('module', 'asset_topic_placement') . '/asset_topic_placement.js', 'file');
        drupal_add_css(drupal_get_path('module', 'asset_topic_placement') . '/asset_topic_placement.css', 'file');

    }
}