/*
* Purpose of this module is to create site structure report into csv file
*
*/

<?php

function site_structure_report_menu() {
    $items = array();
    $items['generate_report'] = array(
        'title' => 'Generate Site Structure Taxonomy Report',
        'page callback' => '_export_report',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE
    );
    return $items;
}

function _export_report()
{

}