<?php

 function cmp_misc_views_query_alter(&$view, &$query) {

     $type = '';

     switch ($view->name){
         case 'search_files_v':
             $type = '\'file_content_type\'';
             break;
         case 'search_content_v':
             $type = '\'file_content_type\', \'multimedia_content_type\', \'state_details\','
             .' \'text_content_type\', \'directory_record_content_type\' ,\'html_content_type\'';
             break;
         case 'search_text_multimedia_html_v':
            $type = '\'multimedia_content_type\', \'text_content_type\' ,\'html_content_type\'';
             break;
         case 'search_state_details_v':
             $type = '\'state_details\'';
             break;
         case 'search_directory_records_v':
             $type = '\'directory_record_content_type\'';
             break;
     }

     if (in_array($view->name, array('search_text_multimedia_html_v', 'search_content_v', 'search_files_v', 'search_state_details_v', 'search_directory_records_v'))) {
         $k = 0;
         foreach ($query->where[1]['conditions'] as $w) {

             if ($w['field'] == 'node_node_revision__field_data_field_owner.field_owner_target_id') {
                 $query->add_where(1, 'users_field_data_field_owner.name', $w['value'], 'LIKE');
                 unset($query->where[1]['conditions'][$k]);
             }
             $k++;
         }
         $latest_vids = array();
         $res = db_query('SELECT hid FROM workbench_moderation_node_history w INNER JOIN node n ON n.nid=w.nid WHERE n.type IN (' . $type . ') AND is_current=1');
         foreach ($res as $r) {
             $latest_vids[] = $r->hid;
         }
         $query->add_where(1, 'node_node_revision__workbench_moderation_node_history.hid', $latest_vids, 'IN');
     }

}


