<?php

/*
 * Implements HOOK_menu()
 */
function repo_sync_menu() {

    $items = array();
    
    // Configuration page URL handler
    $items['admin/repo-sync/ui'] = array(
        'title' => 'Repo-Sync Settings',
        'description' => 'Setup and manage a Git Repository sync',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('repo_sync_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM
    );

    // Trigger callback URL handler
    $items['admin/repo-sync/trigger-sync'] = array(
        'title' => 'Repo-Sync Trigger',
        'description' => 'Setup and manage a Git Repository sync',
        'page callback' => 'repo_sync_triggerSyncMenuCallback',
        'access callback' => 'repo_sync_true',
        'type' => MENU_CALLBACK
    );

    return $items;
}

function repo_sync_true() {
    return true;
}

function repo_sync_form() {

    //dsm('@TODO - White-list directory-jail');

    $triggerUrl = 'https://'.$_SERVER['HTTP_HOST'].'/admin/repo-sync/trigger-sync';

    $form = array();

    $form['actions'] = array(
        '#type' => 'fieldset',
        '#title' => 'Actions',
        '#collapsible' => true,
        '#collapsed' => true,
    );

    $form['actions']['dosyncnow'] = array(
        '#type' => 'submit', 
        '#value' => 'Trigger Sync Now', 
    );

    $form['trigsettings'] = array(
        '#type' => 'fieldset',
        '#title' => 'Sync Trigger',
        '#collapsible' => true,
        '#collapsed' => false,
    );

    $form['trigsettings']['secret'] = array(
        '#type' => 'textfield', 
        '#title' => 'Sync-Trigger Security Key', 
        '#description' => "This will be the string expected when a bit hits; <i>{$triggerUrl}?key=<b>SecurityKeyHere</b></i>",
        '#default_value' => repo_sync_settings('secret'), 
        '#size' => 100, 
        '#required' => TRUE,
    );

    $form['reposrc'] = array(
        '#type' => 'fieldset',
        '#title' => 'Source Repository',
        '#collapsible' => true,
        '#collapsed' => false,
    );

    $form['reposdest'] = array(
        '#type' => 'fieldset',
        '#title' => 'Destination Repository',
        '#collapsible' => true,
        '#collapsed' => false,
    );

    $form['reposrc']['src'] = array(
        '#type' => 'textfield', 
        '#title' => 'Git-Repository HTTPS-URL', 
        '#field_prefix' => 'HTTPS://',
        '#description' => 'Source repository to pull files from.',
        '#default_value' => repo_sync_settings('src'), 
        '#size' => 100, 
        '#required' => TRUE,
    );

    $form['reposrc']['srcuser'] = array(
        '#type' => 'textfield', 
        '#title' => 'Account Username', 
        '#default_value' => repo_sync_settings('srcuser'), 
        '#size' => 25, 
        '#required' => TRUE,
    );

    $form['reposrc']['srcpass'] = array(
        '#type' => 'password', 
        '#title' => 'Account Password', 
        '#attributes' => array('value' => repo_sync_settings('srcpass')),
        '#size' => 25, 
        '#required' => TRUE,
    );

    $form['reposrc']['srcbranch'] = array(
        '#type' => 'textfield', 
        '#title' => 'Branch Name', 
        '#default_value' => repo_sync_settings('srcbranch'), 
        '#size' => 25, 
        '#required' => TRUE,
    );

    $form['reposrc']['srcwlistpath'] = array(
        '#type' => 'textfield', 
        '#title' => 'White-List Path', 
        '#default_value' => repo_sync_settings('srcwlistpath'), 
        '#description' => 'Enter the relative path to the white-list in the source repsoitory.',
        '#size' => 25, 
        '#required' => TRUE,
    );

    $form['reposdest']['dest'] = array(
        '#type' => 'textfield', 
        '#title' => 'Git-Repository HTTPS-URL', 
        '#field_prefix' => 'HTTPS://',
        '#description' => 'Destination repository to place new files into.',
        '#default_value' => repo_sync_settings('dest'), 
        '#size' => 100, 
        '#required' => TRUE,
    );

    $form['reposdest']['destuser'] = array(
        '#type' => 'textfield', 
        '#title' => 'Account Username', 
        '#default_value' => repo_sync_settings('destuser'), 
        '#size' => 25, 
        '#required' => TRUE,
    );

    $form['reposdest']['destpass'] = array(
        '#type' => 'password', 
        '#title' => 'Account Password', 
        '#attributes' => array('value' => repo_sync_settings('destpass')),
        '#size' => 25, 
        '#required' => TRUE,
    );

    $form['reposdest']['destbranch'] = array(
        '#type' => 'textfield', 
        '#title' => 'Branch Name', 
        '#default_value' => repo_sync_settings('destbranch'), 
        '#size' => 25, 
        '#required' => TRUE,
    );

    $form['delete'] = array(
        '#prefix' => '<br/>',
        '#type' => 'submit',
        '#value' => t('Save'),
    );

    return $form;
}

function repo_sync_form_validate($form, $form_state) {

    if ( strpos($form_state['input']['src'], 'http://') === 0 ) {
        form_set_error('src', 'Use of insecure HTTP is unacceptable, please use secure HTTPS.');
    }

    if ( strpos($form_state['input']['dest'], 'http://') === 0 ) {
        form_set_error('dest', 'Use of insecure HTTP is unacceptable, please use secure HTTPS.');
    }

    if ( strpos($form_state['input']['src'], '@') !== false ) {
        form_set_error('src', 'Please remove any username or passwords from the target-URL.');
    }

    if ( strpos($form_state['input']['dest'], '@') !== false ) {
        form_set_error('dest', 'Please remove any username or passwords from the target-URL.');
    }

    if ( substr(strtolower($form_state['input']['srcwlistpath']), -4) !== '.txt' ) {
        form_set_error('srcwlistpath', 'The white-list is expected to be a <b>.txt</b> file.');
    }

}

function repo_sync_form_submit($form, $form_state) {

    // strtolower
    $form_state['input']['src'] = strtolower($form_state['input']['src']);
    $form_state['input']['dest'] = strtolower($form_state['input']['dest']);

    // Trim beginning https:// if present
    if ( substr($form_state['input']['src'], 0, 8) === 'https://' )
        $form_state['input']['src'] = substr($form_state['input']['src'], 8);
    if ( substr($form_state['input']['dest'], 0, 8) === 'https://' )
        $form_state['input']['dest'] = substr($form_state['input']['dest'], 8);

    // Action processing
    if ( $form_state['input']['op'] === 'Trigger Sync Now' ) {
        repo_sync_triggerSync();
        return;
    }

    // Unset any data we dont need to save into the database
    unset($form_state['op']);
    unset($form_state['form_build_id']);
    unset($form_state['form_token']);
    unset($form_state['form_id']);

    // Now lets just throw everything in $form_state into the database
    variable_set('repo_sync_settings', $form_state['input']);
}

function repo_sync_settings($getSetting = 'ALL') {

    $data = variable_get('repo_sync_settings', array());

    if ( $getSetting !== 'ALL' ) {
        if ( !isset($data[$getSetting]) ) $data[$getSetting] = null;
        $data = $data[$getSetting];
    }

    return $data;
}

/**
 * void repo_sync_triggerSyncMenuCallback()
 *
 * A menu-callback handler. This is really just a (security processor) wrapper-function
 * for the repo_sync_triggerSync() function - which is what does the real logic.
 *
 * [!!]WARNING[!!] => THIS FUNCTION WILL TERMINATE THE PHP-THREAD
 */
function repo_sync_triggerSyncMenuCallback() {

    // Kill anything that Drupal was about to print out
    @ob_end_clean();
    while ( @ob_end_clean() );
    header("Content-Type:text/plain");

    // Don't continue if we are not ready yet
    if ( count(repo_sync_settings()) === 0 ) {
        repo_sync_printAndLog('Error - This service is not yet setup');
        exit();
    }

    // Verify security key
    $expectKey = repo_sync_settings('secret');
    if ( empty($expectKey) || empty($_REQUEST['key']) || $_REQUEST['key'] !== $expectKey ) {
        repo_sync_printAndLog('Error - Incorrect security key provided.');
        exit();
    }

    // Fire the function that does the real logic
    repo_sync_triggerSync();
}

/**
 * [@TODO] repo_sync_triggerSync()
 *
 * Executes the logic necessary to sync the file(s) from one repo into the other.
 */
function repo_sync_triggerSync($settings = 'ASSUME-DEFAULT') {

    // Get settings from the database unless overridden in function-call
    if ($settings === 'ASSUME-DEFAULT') $settings = repo_sync_settings('ALL');
    //dsm($settings); return;

    // Prepare process pipes
    $descriptorspec = array(
        0 => array('pipe', 'r'), // stdin is a pipe that the child will read from
        1 => array('pipe', 'w'), // stdout is a pipe that the child will write to
        2 => array('pipe', 'r')  // stderr is a file to write to
    );

    // Create a working directory
    $wdir = '/tmp/gitsync'.time();
    if ( !@mkdir($wdir) ) {
        repo_sync_printAndLog('ERROR - Could not create directory '.$wdir);
        return;
    }
    if ( !@mkdir($wdir.'/src') ) {
        repo_sync_printAndLog('ERROR - Could not create directory '.$wdir);
        return;
    }
    if ( !@mkdir($wdir.'/dest') ) {
        repo_sync_printAndLog('ERROR - Could not create directory '.$wdir);
        return;
    }

    // Pull down the source-repo
    $cloneUrl = 'https://'.$settings['srcuser'].':'.$settings['srcpass'].'@'.$settings['src'];
    $rslt = `git clone '{$cloneUrl}' {$wdir}/src 2>&1`;
    if ( strpos($rslt, 'Authentication failed') !== false ) {
        repo_sync_printAndLog('Error - Could not pull down source-repository due to authentication-error.');
        return;
    }
    
    // Switch to target branch (source repo)
    $rslt = `cd {$wdir}/src; git checkout {$settings['srcbranch']} 2>&1`;
    if ( strpos($rslt, 'error') === 0 ) {
        repo_sync_printAndLog(
            "Error - Could not switch to branch \"{$settings['srcbranch']}\" in source-repo. "
                ."Are you sure this branch exsist on the server?"
        );
        return;
    }

    // Pull down the destination repo
    $cloneUrl = 'https://'.$settings['destuser'].':'.$settings['destpass'].'@'.$settings['dest'];
    $rslt = `git clone '{$cloneUrl}' {$wdir}/dest 2>&1`;
    if ( strpos($rslt, 'Authentication failed') !== false ) {
        repo_sync_printAndLog('Error - Could not pull down source-repository due to authentication-error.');
        return;
    }

    // Switch to target branch (source repo)
    $rslt = `cd {$wdir}/dest; git checkout {$settings['destbranch']} 2>&1`;
    if ( strpos($rslt, 'error') === 0 ) {
        repo_sync_printAndLog(
            "Error - Could not switch to branch \"{$settings['destbranch']}\" in destination-repo. "
                ."Are you sure this branch exsist on the server?"
        );
        return;
    }

    // Get while-list targets
    $wlPath = $wdir . '/src/' . $settings['srcwlistpath'];
    $whiteList = array();
    if ( !file_exists($wlPath) ) {
        repo_sync_printAndLog("Error - No white-list found at {$settings['srcwlistpath']} in the source-repository.");
        return;
    }
    $whiteList = file($wlPath, FILE_SKIP_EMPTY_LINES + FILE_IGNORE_NEW_LINES);
    if ( $whiteList === false ) {
        repo_sync_printAndLog("Error - Could not read white-list file, are permissions set correctly?");
        return;
    }

    // Copy over white-listed files
    foreach ( $whiteList as $lineNumb => &$entry ) {

        // Get entry information
        $entry = trim(trim($entry), "\"'");
        $fileRelSrc = $entry;
        $fileRelDest = $entry;

        // Determine paths
        $filePathSrc = $wdir.'/src/'.$fileRelSrc;
        $filePathDest = $wdir.'/dest/sites/all/themes/usa/'.$fileRelDest;

        // Security
        if ( strpos($filePathSrc, '..') !== false || strpos($filePathDest, '..') !== false ) {
            repo_sync_printAndLog("Warning - White-list entry contains unacceptable \"..\" in row {$lineNumb}");
            continue;
        }

        if ( strpos($fileRelDest, '*')  !== false) {
            $starFiles = explode("\n",`ls $filePathDest`);
            foreach ( $starfiles as $starFile ) {
                $whiteList[] = trim($starFile);
            }
            continue;
        }

        // Existence check
        if ( !file_exists($filePathSrc) ) {
            $msg = "Warning - White-listed file {$fileRelSrc} does not exist in source-repo, skipping...";
            repo_sync_printAndLog($msg);
            continue;
        }

        // Copy the file over into the dest-repo
        @unlink($filePathDest);
        if ( !copy($filePathSrc, $filePathDest) ) {
            $msg = "Error - Failed to copy \"{$filePathSrc}\" to \"{$filePathDest}\". Permissions? Skipping...";
            repo_sync_printAndLog($msg);
            continue;
        } else {
            repo_sync_printAndLog("Notice: Copied \"{$filePathSrc}\" to \"{$filePathDest}\" successfully.");
        }
    }

    // Add all file-changes under Git-tracking
    `cd {$wdir}/dest; git add -A;`;

    // Push up the new files
    $rslt = `cd {$wdir}/dest; git commit -m 'test'; git push`;
    if ( strpos($rslt, 'nothing to commit') !== false ) {
        repo_sync_printAndLog("Warning: Nothing was pushed in repo-sync, no files appear to be updated.");
    } else {
        if ( strpos($rslt, 'error') !== false ) {
            repo_sync_printAndLog("Error: An unexpected error occurred during git-push.");
            return;
        } else {
            $retLines = explode("\n", trim($rslt));
            repo_sync_printAndLog("Notice: Repo-sync completed successfully. Git returned: ".$retLines[count($retLines)-1]);
        }
    }

    // Clean up
    `rm -r {$wdir}`;

}

function repo_sync_printAndLog($strMessage) {

    print $strMessage;

    error_log($strMessage);

    dsm( $strMessage );

    //@TODO - add to a log specific log file or table

    //@TODO - add to a log watchdog-API/syslog
}
